
sudo: required
dist: trusty
os: linux
language: minimal
cache:
  directories:
  - depends/built
  - depends/sdk-sources
  - $HOME/.ccache
env:
  global:
    - MAKEJOBS=-j3
    - RUN_TESTS=false
    - CHECK_DOC=0
    - CHECK_LOGPRINT=0
    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
    - WINEDEBUG=fixme-all
  matrix:
# ARM - Raspberry Pi
#    - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf" CHECK_DOC=1 CHECK_LOGPRINT=1 GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
# Win32
    - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.6 bc" GOAL="deploy" BITCOIN_CONFIG="--enable-reduce-exports"
# 32-bit Linux
 #   - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib bc python3-zmq" GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash" PYZMQ=true
# Win64
#    - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine1.6 bc" GOAL="deploy" BITCOIN_CONFIG="--enable-reduce-exports"
# 64bit Linux
 #   - HOST=x86_64-unknown-linux-gnu PACKAGES="bc python3-zmq" DEP_OPTS="NO_UPNP=1 DEBUG=1" GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports CPPFLAGS=-DDEBUG_LOCKORDER" PYZMQ=true
# Cross-Mac
#    - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports" OSX_SDK=10.11 GOAL="deploy"

before_install:
    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
install:
    - if [ "$PYZMQ" = "true" ]; then pip install pyzmq --user ; fi
    - if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
before_script:
    - if [ "$CHECK_DOC" = 1 ]; then contrib/devtools/check-doc.py; fi
    - sudo chmod +x contrib/devtools/logprint-scanner.py
    #- if [ "$CHECK_LOGPRINT" = 1 ]; then contrib/devtools/logprint-scanner.py; fi
    - unset CC; unset CXX
    - mkdir -p depends/SDKs depends/sdk-sources
    - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
    - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
    - make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
script:
    - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
    - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
    - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
    - BITCOIN_CONFIG_ALL=" --disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
    - depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
    - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
    - ./configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
    - make distdir PACKAGE=bitcoin VERSION=$HOST
    - cd bitcoin-$HOST
    - ./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
    - make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && travis_wait 30 make $GOAL V=1 ; false )
    - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
    #- if [ "$RUN_TESTS" = "true" ]; then travis_wait 30 make $MAKEJOBS check VERBOSE=1; fi
    #- if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.py --coverage; fi
after_script:
    - echo $TRAVIS_COMMIT_RANGE
    - echo $TRAVIS_COMMIT_LOG
before_deploy:
  - sudo chmod +x $TRAVIS_BUILD_DIR/contrib/travis/travis-artifacts/collect-artifacts.sh
  - ls $TRAVIS_BUILD_DIR/src
  - ls $TRAVIS_BUILD_DIR/src/qt
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: bC0z9vj2YiqzjVYFW4er96EKp1HhJVmH0LCqPvXbd7JPoC8ySYNK2UZj27LGB83e/kIdaEsq2HgYpcmSVMk1/iLQCJxnTQj6CrIq3Xr7KvhKsqNpVGv8cr36CiB20x0PNMa+6KuTvcfEJYOReBxtIVZSXhBXXLnuDXmD6E5/IHclnFHKH987u4QSzSVSnsZHOTbvJ1zIEnsrXtVZRhyzVePm5alNYH6FwDvtreeGg9FR1B+JdMpd3fPDKWuUrruPRkZeWNf5WgJYVQMJUtm7E+gkCLRI8BPhT8tj2EjTdz2pvwilRPt5Qk+qictP/Bp2NnQSZIP7k/yZ6bw9mdz6q/jR4h4izzD1SV+dhNazUB2bLGkSnoiu8UtL8ms2VjQmxZKePudVJLmWceq9C9uM7dc80kHNpVovgZvpWkKKc/7/J3mNP6+15h6f5f9AFd4+IaxLh0FznuC19Rjefim5JnXbS+DN8QLnjdkT7lp5QEhTdJD/+uvypeM2O2sH80ku7mwAQRRcg9G4NObStb6JldexpNr893CqyOu4AtC/k3tLuOk+S2SBgu7Enc1clg7npBqGvb+2spOwnFjqkT/xVl8S7cjiaUjMdtlGaPz0jD9RltgU/xQTu5qPq6DfZI1la+DIyEUFhjgMRQe9CdX961R7NX5KDG0kaieVr+odJHI= 
    file_glob: true
    file: $TRAVIS_BUILD_DIR/bitcoin-i686-w64-mingw32/jiyo-1.0.3-win32-setup.exe
    on:
      branch: master
      repo: nashanas/jiyo-core
      tags: false
